### ISSUE TITLE
Print normal form: sorting predicate not displayed

### ISSUE THREAD

**Issue by yhamoudi** [ProjetPP/PPP-CLI#6]
Ex: `What is the largest city in Germany?`

**Comment by yhamoudi** [comment]
Wanted: 
![image](https://cloud.githubusercontent.com/assets/6659728/6022864/47bd78a8-abc0-11e4-9363-d9690ed06b72.png)

**Comment by progval** [comment]
Fixed in https://github.com/ProjetPP/PPP-datamodel-Python/commit/dbc5fbf0411c2d1726c60f671ab4d406bf649ec5
